### PR TITLE
Fix #526 - use extension methods for AppendFormat

### LINKED ISSUE #526: Add extension methods on HtmlContentBuilder for String.Format style formatting

### PR DESCRIPTION
**Pull request by rynowak**
These changes make TagHelperContent with the IHtmlBuilder pattern, but
retain the signatures returning TagHelperContent.

Removed a bunch of tests that are no redundant with tests for the
extension methods in HttpAbstractions. Kept a few explemars in place to
ensure that the basic plumbing functions as desired.

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
:shipit:. We might want to consider eventually moving `TagHelperContent` HTML building methods to only return `IHtmlContentBuilder`. If we have a rich enough HTML content building surface chaining only `IHtmlContentBuilder` may suffice.

**Comment by rynowak** [comment]
@NTaylorMullen - the reason I kept it as-is is that `IHtmlContentBuilder` and friends are in a different namespace

**Comment by NTaylorMullen** [comment]
@rynowak oh duh, ya that was the reason. Ugh.

**Comment by rynowak** [comment]
The other change we could make would be to define the extensions on `<T> where T : IHtmlContentBuilder`, but that's ugly.

**Comment by NTaylorMullen** [comment]
Hmm, that honestly doesn't sound too bad compared to what we're doing here (duplicating everything)

**Pull request merged**
