### PR TITLE
Make RazorCompileOnPublish the default

### PR DESCRIPTION
**Pull request by rynowak**

### CODE REVIEW

**Comment by rynowak** [comment]
We will need to make a change in the WebSDK related to this to make precompilation non-default there.

**Comment by pranavkm** [comment]
> We will need to make a change in the WebSDK related to this to make precompilation non-default there.

Make it non-default conditionally?

**Comment by pranavkm** [comment]
Tests are failing btw. Could you check what's up with that?

**Comment by rynowak** [comment]
> Make it non-default conditionally?

Not sure I know what that means. I'm meeting with those people this morning to discuss.

**Comment by pranavkm** [comment]
The issue as I understand it is that we want users targeting Asp.Net Core 2.0.0 to be able to continue getting precompilation when they use the 2.1.0 SDK.

**Comment by rynowak** [comment]
Yes that's correct 😆 - now I get what you mean. We're meeting with those peeps this morning.

**Pull request merged**
