### PR TITLE
Don't capture asynclocals onto Timer

### PR DESCRIPTION
**Pull request by benaadams**
Pattern is a workaround for not having api https://github.com/dotnet/corefx/issues/26523

Also a bit less captured scope onto the Task.StartNew

/cc @davidfowl

### CODE REVIEW

**Comment by rynowak** [comment]
I'm sure this can't hurt, but is it important? This code doesn't ship in the runtime.

**Comment by benaadams** [comment]
If it runs in VS its probably capturing stranger things :)

**Comment by rynowak** [comment]
image

**Comment by rynowak** [comment]
Thanks @benaadams - I'm going to merge this and then apply the new package on top.

**Pull request merged**
