### PR TITLE
Adding VSTS file

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
It seems that there is a consistent hang on Linux for Razor soon after we see this suspicious test that doesn't appear on TeamCity:

```
Invalid argument(s).
2018-06-07T23:35:54.2252397Z   Usage:   
2018-06-07T23:35:54.2269856Z       dotnet razorpagegenerator <root-namespace-of-views> [path]
2018-06-07T23:35:54.2293757Z   Examples: 
2018-06-07T23:35:54.2309237Z       dotnet razorpagegenerator Microsoft.AspNetCore.Diagnostics.RazorViews
2018-06-07T23:35:54.2325333Z           - processes all views in "Views" subfolders of the current directory
2018-06-07T23:35:54.2341856Z       dotnet razorpagegenerator Microsoft.AspNetCore.Diagnostics.RazorViews c:\project
2018-06-07T23:35:54.2609231Z           - processes all views in "Views" subfolders of c:\project directory
2018-06-07T23:35:54.2625971Z   
2018-06-07T23:35:54.2639536Z   
2018-06-07T23:35:54.2654103Z     Generating code files for views in /opt/vsts/work/1/s/test/RazorPageGenerator.Test/TestFiles/Views
2018-06-07T23:35:54.2807679Z       Generating code file for view TestView.cshtml...
2018-06-07T23:35:54.2822465Z         Inlining file TestFile.js
2018-06-07T23:35:54.2840164Z         Done!
```

@NTaylorMullen do you have time to look into this or know of another Razor person who does?

**Comment by ryanbrandenburg** [comment]
Talked to Taylor in person, I'm going to see about getting him an image of the build machine that failed.

**Comment by ryanbrandenburg** [comment]
We're stalled on this until we can get a docker image that we can use to diagnose. I've talked to some people on the VSTS team, hopefully they have info soon.

**Comment by ryanbrandenburg** [comment]
This is stalled. Our current thinking is that something is causing the VSTS agent to lose connection with the server (maybe killing a process?), but we can't diagnose that ourselves so we need the VSTS people to look into it.

**Comment by natemcmaster** [comment]
Is this better now that we have more agents?

**Comment by ryanbrandenburg** [comment]
Looks like no, I don't think it's a matter of number of build agents so much as a communication problem between agent and server. Possibly our scripts hang in VSTS for some weird environment reason, but we're looking into it.

**Comment by natemcmaster** [comment]
I've been chatting with the VSTS folks. It looks like there is something in the VSTS infrastructure which doesn't play nice with background processes, such as rzc. I'm going to disable tests on VSTS Linux builds for now since we have coverage that works on Jenkins and TeamCity.

**Comment by natemcmaster** [comment]
@rynowak are there known issues with the tests "Queue_ProcessesNotifications_AndGoesBackToSleep"? It consistently fails on Windows in VSTS

image

**Comment by natemcmaster** [comment]
Queue_ProcessesNotifications_AndRestarts failed on Jenkins, so I'm going to open this as a flaky bug issue.

@HaoK can you review?

**Comment by natemcmaster** [comment]
https://github.com/aspnet/Razor/issues/2506

**Comment by rynowak** [comment]
Yeah I think it's F L A K Y

**Comment by natemcmaster** [comment]
I've opened https://github.com/aspnet/Razor/issues/2506 to follow up on flaky tests and https://github.com/aspnet/Razor/issues/2507 to follow up on re-enabling Linux.

**Pull request merged**
