### PR TITLE
Update repo to utilize ApiCheck.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- Re-enabled api check for `Microsoft.AspNetCore.Razor` and `Microsoft.AspNetCore.Razor.Runtime`. This resulted in me adding known breaking changes for the packages.
- Added empty baseline files for `Microsoft.AspNetCore.Razor.Language`, `Microsoft.AspNetCore.Mvc.Razor.Extensions` and `Microsoft.CodeAnalysis.Razor`.
- Disabled ApiCheck for `Microsoft.CodeAnalysis.Razor.Workspaces`, `Microsoft.CodeAnalysis.Remote.Razor`, `RazorPageGenerator` and `Microsoft.VisualStudio.LanguageServices.Razor` to prevent ApiCheck warnings about missing baselines (we don't ship these packages).

#1107 

Also as a side note, there's a baseline.net45.json in the `Microsoft.AspNetCore.Razor` project; it doesn't seem to be used at all (the project doesn't cross-compile). Thought about removing it but I'm not aware of any cross-cutting concerns with it.

### CODE REVIEW

**Comment by rynowak** [comment]
Can we get rid of the old net45 baseline file? It's not doing anything if it's always ignored

**Comment by NTaylorMullen** [comment]
> Can we get rid of the old net45 baseline file? It's not doing anything if it's always ignored

I'd like to but want to make sure there's not a cross-cutting/cross-repo piece I'm missing. Who would be the right person to run that by?

**Comment by NTaylorMullen** [comment]
> Can we get rid of the old net45 baseline file? It's not doing anything if it's always ignored

Removed it. Looked around/asked around.

**Comment by rynowak** [comment]
:shipit:

**Pull request merged**
