### PR TITLE
Update to StreamRpc 1.1.92

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by rynowak** [comment]
:shipit:

**Comment by pranavkm** [comment]
We're down to one warning in Razor. That should be fixed once we update to Roslyn 2.3.0 RTM (https://github.com/aspnet/Razor/issues/1473). In fact, we could try getting newer builds of Roslyn package (https://github.com/aspnet/CoreCLR/blob/dev/tools/MirrorLatestCoreCLR/restore-projects/Roslyn.proj#L5) and verify this goes away. 

Relevant Roslyn bug https://github.com/dotnet/roslyn/issues/16040 that says updating to `2.3.0-beta3` should address this.

**Comment by mikeharder** [comment]
I chatted with @rynowak, and he agrees we should update to 2.3.0-beta3.  @pranavkm, can you make this chagne today?  Otherwise I can work on it.  I assume it requires changes to both the mirror and Razor, and the version should be set to `2.3.0-beta3-*`.

**Comment by pranavkm** [comment]
I can get it updated.

**Pull request merged**
