### PR TITLE
Add the ability for `TagHelper`s to exist inside templates.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- Previously doing `@<mytaghelper />` was invalid due to how we constructed templates lambdas.

#489

Corresponding MVC PR: https://github.com/aspnet/Mvc/pull/3029

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
Going to create an additional MVC PR (even though nothing breaks) to add functional test coverage of this feature fix.

**Comment by NTaylorMullen** [comment]
@pranavkm this good too?

**Comment by pranavkm** [comment]
:shipit:

**Comment by davidfowl** [comment]
Why is travis failing

**Comment by NTaylorMullen** [comment]
@davidfowl Didn't rebase :smile:

**Comment by NTaylorMullen** [comment]
@davidfowl Nm, looks like I pushed update bits incoherently timeout for a package on mac. Happens every now and then given the occasional instability of the OSX builds :cry:

**Comment by NTaylorMullen** [comment]
@davidfowl re-ran and all good.

**Pull request merged**
