### PR TITLE
Removed `TagHelper` infrastructure `using` statements.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- The using statements had a chance to conflict with user code. Removed them and changed the default configured type names to be full name based.

#580

Mvc PR: https://github.com/aspnet/Mvc/pull/3436

### CODE REVIEW

**Comment by ajaybhargavb** [comment]
:shipit:

**Comment by dougbu** [comment]
:shipit:

**Comment by NTaylorMullen** [comment]
Closing and re-opening with new `global::` changes, looks like the enum change that went in is messing with the number of commits.

**Pull request closed without merging**
