### PR TITLE
Generate line pragmas even for whitespace.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- We need to pre-emptively generate line pragmas to handle C# scenarios which are session based. For instance, if a C# completion session starts at a location without a pragma they capture the origination point; at which point if a user keeps typing we generate a line pragma drastically changing where the copmletion started resulting in a broken C# completion experience.
- Updated test files to reflect new behavior.

This is what this PR enables:
image

#2299

### CODE REVIEW

**Comment by rynowak** [comment]
The idea of this makes sense...

Can we find a way to add this invariant to our tests so that it's **impossible** to introduce a bug? For instance, would it be possible to add the invariant that **all** C# spans appear in our in output. This would make the principle behind this change broadly enforced, and prevent us from having any kind of bug like this in the future.

In principle, this is part of the fix for what you're working on

**Comment by NTaylorMullen** [comment]
> Can we find a way to add this invariant to our tests so that it's impossible to introduce a bug? For instance, would it be possible to add the invariant that all C# spans appear in our in output. This would make the principle behind this change broadly enforced, and prevent us from having any kind of bug like this in the future.

Agree, figured that was covered by [this](https://github.com/aspnet/Razor/issues/2266)

**Comment by rynowak** [comment]
So you're doing it then?

**Comment by NTaylorMullen** [comment]
> So you're doing it then?

Not as part of this issue, It's not nearly a high enough priority. We've had this issue in every version of Razor and it was just recently reported. After we get through the 15.8 issues we can consider.

**Comment by NTaylorMullen** [comment]
@dotnet-bot test OSX 10.12 Release Build please

**Comment by NTaylorMullen** [comment]
@natemcmaster is KoreBuild in a borked state for OSX? Looks like the OSX builds keep failing to find dotnet

**Comment by natemcmaster** [comment]
Yes. Run `build.cmd -update /t:noop` to get the latest korebuild

**Comment by rynowak** [comment]
As I understand it, the problem statement is that you don't get intellisense in empty or whitespace-only C# regions correct? And this is more likely to occur in live-share scenarios due to the way the remote-editor interactions work correct?

So how do you know you fixed all of the cases? You surely fixed this for code blocks containing only whitespace. Are there others?

**Comment by NTaylorMullen** [comment]
> As I understand it, the problem statement is that you don't get intellisense in empty or whitespace-only C# regions correct?

Partially correct, without me personally spending the time to dive into all the pieces that @ToddGrun did the issues seems to be scoped to whitespace pieces in a single line `@{}` only. I've tried out other whitespace scenarios such as `@functions {}` `@{ \r\n }` `@()` and they all work. The bet is that Roslyn behaves odd in the `@{}` scenario. @ToddGrun could probably explain more since he did the initial dive in the original VSTS issue.

**Comment by NTaylorMullen** [comment]
> And this is more likely to occur in live-share scenarios due to the way the remote-editor interactions work correct?

Ya it could be exacerbated in the live share scenario because the completion logic is done on the host.

**Comment by NTaylorMullen** [comment]
@rynowak and I talked offline. Going to leave this as is and get it in.

**Pull request merged**
