### PR TITLE
Don't generate CSharpStatementIRNode for null or whitespace

### PR DESCRIPTION
**Pull request by ajaybhargavb**
PR https://github.com/aspnet/Razor/pull/1115 brought up this issue

@rynowak @NTaylorMullen

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
They should be generated for whitespace. Without the line mappings you wont get IntelliSense in the editor if you invoke it in those locations.

**Comment by ajaybhargavb** [comment]
Ah I see. Is it just the line mappings or the line pragmas as well?

**Comment by NTaylorMullen** [comment]
Just need the line mappings

**Comment by ajaybhargavb** [comment]
👍 I'll send a PR to add them

**Pull request merged**
