### PR TITLE
Enable Razor templates inside of sections.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- Changed the variable used to render templates (`HelperResult`s) so they can be used inside of sections.
- Updated section test file to showcase nested scenario. Also Regenerated existing test files.

#572

### CODE REVIEW

**Comment by pranavkm** [comment]
Would this cause a perf regression?

**Comment by NTaylorMullen** [comment]
lol such a :trollface:

**Comment by pranavkm** [comment]
:shipit:

**Pull request merged**
