### PR TITLE
Using 'nameof' operator instead of magic strings

### PR DESCRIPTION
**Pull request by hishamco**
Using the "nameof" operator instead of magic string will help us if the variable change in the future for whatever the reason

### CODE REVIEW

**Comment by dougbu** [comment]
@hishamco thanks for this cleanup but it isn't clear it's worth doing in the Razor repo at the moment. This repo makes minimal use of `[NotNull]` and that's where all of the `throw ArgumentNullException` checks should be going. How about I make the switch to `[NotNull]` some evening soon and you rebase on top of that to clean up the remaining magic strings?

BTW am I correct that none of the magic strings were actually incorrect in this repo?  If so, wow.

**Comment by hishamco** [comment]
@dougbu  I'm agree with you that string params are correct. BTW using the common NotNull attribute is a cool idea if you do so ..

**Comment by dougbu** [comment]
@hishamco I'll do that tonight or tomorrow. Not exactly my highest priority but I'll get to it...

**Comment by hishamco** [comment]
@dougbu you can check dnx repo there are 21 files needs the same change

**Comment by dougbu** [comment]
@hishamco please rebase now that I've pushed #376  I'll merge your remaining changes tonight.

**Comment by hishamco** [comment]
@dougbu you mean I shall update my fork with the latest changes from the repo

**Comment by dougbu** [comment]
@hishamco yes please

**Comment by hishamco** [comment]
@dougbu sorry i was on a rush because I should travel to home, I rebased before but I faced tiny issue during merge, now I fixed them .. I hope it's ok :)

**Comment by dougbu** [comment]
@hishamco looks good; I'll :shipit: for you

**Comment by hishamco** [comment]
Thanks ..

**Pull request merged**
