### PR TITLE
Remove pragma warning disable 1998

### PR DESCRIPTION
**Pull request by benaadams**
Function doesn't need async

### CODE REVIEW

**Comment by Eilon** [comment]
@rynowak can you review?

**Comment by rynowak** [comment]
:shipit: Looks good to me, thanks @benaadams - I'll merge shortly

**Comment by rynowak** [comment]
FYI did a search and the only suppressions of this warning in MVC were in tests

**Comment by rynowak** [comment]
cacd16fa854996af7ea11e3fd61bff9969022845

**Pull request closed without merging**
